version: "3"
services:
  api:
    container_name: api
    build:
      context: ./build/api
      target: prod
    env_file:
      - build/api/.env
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'

networks:
  default:
    name: app_net

volumes:
  db:
