name: test
on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: go mod download
        run: go mod download
        working-directory: ./app
        env:
          GO111MODULE: on
      - name: go vet
        run: go vet ./...
        working-directory: ./app
